### PR TITLE
Patching cleanup

### PR DESCRIPTION
**Pull request by zsoltbalogh**
These changes are needed to support all types of hotfixes and fix packs.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-docker/compare/9a73684f8c...f8ae2b8c6c

**Comment by brianchandotcom** [comment]
@zsoltbalogh please see my changes.. I'll publish again later today.

**Comment by brianchandotcom** [comment]
@zsoltbalogh are you sure you need to do these 3 dirs specifically?

	rm -rf /opt/liferay/osgi/state/*
	rm -rf /opt/liferay/tomcat/temp/*
	rm -rf /opt/liferay/tomcat/work/*

I have a feeling that only state is needed.

**Comment by zsoltbalogh** [comment]
This is what support is still recommending. Let's go with these for now and we'll remove others once we can clarify. I've asked ER to look into this (incl. osgi/state) in 2020 and we'll clean up after we actually clarified what's exactly necessary for which FP level.

**Pull request closed without merging**
