### PR TITLE
5 os functions

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
hey @mdelapenya I dug in a bit more, and the logic you have for Linux and OSX is slightly different.

Theoretically, if you run this right between changes of days, then you could get 2 different dates. That is not possible with the Linux version because I parse in the actual current_date.

I found this online  https://unix.stackexchange.com/questions/115736/unable-to-use-date-command-to-change-specific-date-format-in-bash-shell-on-os-x to help me. Can you test this on OSX?

See my attempt for OSX compatible date in faa9f6fd7fa45a94cc3d9147e117da6b6c32775a

Can you resend on top of this for "stat" and follow the same format as what I did? Please double check that the OSX stat and the Linux stat is doing the exact the same thing. Thx!

**Comment by mdelapenya** [comment]
Using your approach in my Mac (Mojave):
Attempt 1:
```shell
/usr/bin/date -jf "%a %b %e %H:%M:%S %Z %Y" $(date) "+%Y%m%d%H%M"
zsh: no such file or directory: /usr/bin/date
```
Attempt 2: 
```
$ which date
/bin/date

/bin/date -jf "%a %b %e %H:%M:%S %Z %Y" $(date) "+%Y%m%d%H%M" 
Failed conversion of ``Tue'' using format ``%a %b %e %H:%M:%S %Z %Y''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```

**Comment by brianchandotcom** [comment]
When you just type "date", what do you get? @lionah and I just tested this on a Mac/ Mojave and it works for us. I wonder if it's a Spanish "date" return value?

**Comment by brianchandotcom** [comment]
@mdelapenya I pushed a fix for the /bin/ path, please try ? We weren't able to reproduce the Tue format issue.

**Comment by mdelapenya** [comment]
I found the issue, which was on my side:

Wrong: copied from the scripts and executed in the terminal:
```shell
/bin/date -jf "%a %b %e %H:%M:%S %Z %Y" $(date) "+%Y%m%d%H%M" 
```
Good (same as in the scripts)
```shell
/bin/date -jf "%a %b %e %H:%M:%S %Z %Y" "$(date)" "+%Y%m%d%H%M" 
```
Note the quotes around $(date).

Thanks!

PS: working on the `stat` version :-)

**Pull request closed without merging**
