### PR TITLE
Hooking points - different solution

### PR DESCRIPTION
**Pull request by zsoltbalogh**
We should separate out scripts for child image developers (like Cloud) from scripts which are developed for the container level, otherwise child image developers would need hacks if they want to allow container level scripts to be run.

Recommended paths:
/usr/local/liferay/scripts -> Changes by child images (so these changes are stored in the images, copied there by a Dockerfile)
/mnt/liferay/ -> Changes which are applied when the container is starting up - these can be different every time there's a container startup

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arbetts** [comment]
I think we'll need this modification https://github.com/zsoltbalogh/liferay-docker/pull/2

**Comment by zsoltbalogh** [comment]
@brianchandotcom , when will you have a chance to review this? I've pushed @arbetts ' first change and I haven't merged the second yet as it was previously working code and I'd like to reproduce it before merging in.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-docker/compare/32db89bbda...cc676c8da1

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-docker/compare/15ac53aabf...1da1c99fe0

**Comment by brianchandotcom** [comment]
Sorry it took so long to review, this was very good.

Thanks @zsoltbalogh @arbetts

**Comment by gamerson** [comment]
💯

**Pull request closed without merging**
