### PR TITLE
LRCI-2015

### PR DESCRIPTION
**Pull request by zsoltbalogh**

### CODE REVIEW

**Comment by zsoltbalogh** [comment]
@pyoo47, I had some SF changes, I hope I did not break anything.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-docker/compare/e061935420...03c40b0c8b

**Comment by brianchandotcom** [comment]
@zsoltbalogh just 03c40b0c8b3cfc9d273139e2b4205a12afe759ff

**Comment by brianchandotcom** [comment]
@zsoltbalogh and 1cb8efd60863c0e8a1ded32573f8a4e39e318460

**Pull request closed without merging**
