### PR TITLE
LPD-32410 More than one 2024.q2 patch release being promoted in releases.json

### PR DESCRIPTION
**Pull request by kiwm**
Related issue: https://liferay.atlassian.net/browse/LPD-32410

### CODE REVIEW

**Comment by kiwm** [comment]
cc: @natocesarrego

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-docker/compare/13a06621d0...385ef4ed8d

**Comment by brianchandotcom** [comment]
@natocesarrego @kiwm 0 changes from me

**Comment by brianchandotcom** [comment]
@natocesarrego @kiwm  nevermind, I did change 64382c9efd9da2fcd7dc2634d22e4dfe6eb9f2a1

**Pull request closed without merging**
